#!/usr/bin/env bash
# =============================================================================
# capture.sh - build and run wave_capture_tb, producing wave.vcd.
#
#   ./verification/capture.sh
#
# The VCD it writes is the input to doc/tools/waveforms/mkwaves.py, which cuts
# the user guide's timing figures out of it. Neither the VCD nor the build
# directory is tracked - both are in .gitignore, and both are regenerated by
# running this.
#
# This is not part of the regression. It checks nothing; run_all.sh does the
# checking. Its only job is to record a real simulation so the figures in the
# documentation cannot drift away from the RTL.
# =============================================================================
set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/.." && pwd)"

# Finding Verilator - the same two installation shapes the regression handles.
# A distro or source install puts `verilator` on PATH and knows its own root; a
# pip install puts the binary inside the Python package and does NOT set
# VERILATOR_ROOT, without which the wrapper cannot find its include/ tree.
if ! command -v verilator >/dev/null 2>&1; then
    PIPROOT=$(python3 -c 'import verilator,os;print(os.path.dirname(verilator.__file__))' 2>/dev/null)
    if [ -n "${PIPROOT:-}" ] && [ -x "$PIPROOT/bin/verilator" ]; then
        export VERILATOR_ROOT="$PIPROOT"
        export PATH="$PIPROOT/bin:$PATH"
    else
        echo "error: verilator not found in PATH" >&2
        echo "       (pip install verilator, or your distro's package)" >&2
        exit 127
    fi
fi

# Precompiled-header workaround, applied only when the installed makefile
# actually has CFG_CXXFLAGS_PCH_I empty - the PyPI wheel does, and the failure
# it causes ("linker input file not found") looks nothing like a missing flag.
PCHFIX=()
VMK="${VERILATOR_ROOT:-}/include/verilated.mk"
if [ -f "$VMK" ] && grep -qE '^CFG_CXXFLAGS_PCH_I[[:space:]]*=[[:space:]]*$' "$VMK"; then
    PCHFIX=(-MAKEFLAGS "CFG_CXXFLAGS_PCH_I=-include")
fi

# Build directory. SDCARD_SIM_OBJDIR redirects it for the same reason the
# regression honours it: some container and network mounts permit writes but
# not unlinks, and Verilator's generated makefile removes its own temporaries.
OBJROOT="${SDCARD_SIM_OBJDIR:-$HERE}"
mkdir -p "$OBJROOT"
OBJ="$OBJROOT/obj_dir_wave"
rm -rf "$OBJ"

P="$ROOT/rtl/avalon_mm_sdcard_controller"

verilator --binary --timing --trace -j "$(nproc)" \
    -CFLAGS "-std=c++20" "${PCHFIX[@]}" \
    -Wno-DECLFILENAME -Wno-WIDTHTRUNC -Wno-WIDTHEXPAND -Wno-UNUSEDPARAM \
    -Wno-UNUSEDSIGNAL -Wno-SYNCASYNCNET -Wno-MULTIDRIVEN -Wno-PROCASSINIT \
    -Wno-BLKSEQ -Wno-VARHIDDEN -Wno-ASCRANGE -Wno-LATCH -Wno-CASEINCOMPLETE \
    --Mdir "$OBJ" -o wcap \
    "${P}_pkg.sv" "${P}_crc.sv" "${P}_clkgen.sv" "${P}_spi_phy.sv" \
    "${P}_fifo.sv" "${P}_dma.sv" "${P}_seq.sv" "${P}_regs.sv" "${P}.sv" \
    "$ROOT/tb/spi_card_model.sv" "$ROOT/tb/avalon_mm_mem_model.sv" \
    "$HERE/wave_capture_tb.sv" \
    --top-module wave_capture_tb > "$OBJROOT/capture_build.log" 2>&1

if [ ! -x "$OBJ/wcap" ]; then
    echo "error: wave_capture_tb did not build - see $OBJROOT/capture_build.log" >&2
    grep -E '^%Error' "$OBJROOT/capture_build.log" | head -10 >&2
    exit 1
fi

# The bench writes wave.vcd into its own working directory, so run it from the
# directory the renderer expects to find it in.
cd "$HERE" && "$OBJ/wcap"
rc=$?

if [ $rc -ne 0 ] || [ ! -s "$HERE/wave.vcd" ]; then
    echo "error: no wave.vcd produced" >&2
    exit 1
fi

echo "wave.vcd written to $HERE ($(du -h "$HERE/wave.vcd" | cut -f1))"
echo "render the figures with:"
echo "  python3 $ROOT/doc/tools/waveforms/mkwaves.py $HERE/wave.vcd"
